#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: message-exchange
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: -1
